<?php
define('IN_APP',true);
require_once __DIR__.'/../includes/config.php';
require_once __DIR__.'/../includes/layout.php';
requireAdmin();
ini_set('max_execution_time',300);
header('Cache-Control: no-store,no-cache,must-revalidate');

$db = db();
$routers = $db->query("SELECT * FROM routers WHERE is_active=1 AND use_mikhmon=1 ORDER BY is_main DESC, name ASC")->fetchAll();

startPage('Laporan Penjualan');
?>
<style>
@keyframes spin{to{transform:rotate(360deg)}}

/* ── Router cards ── */
.rcard{background:#fff;border:1.5px solid var(--g200);border-radius:12px;padding:13px 16px;
       display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;
       transition:.2s;cursor:pointer;margin-bottom:8px}
.rcard:hover{border-color:var(--blue);box-shadow:0 4px 16px rgba(27,63,166,.12);transform:translateY(-1px)}
.rcard.disabled{opacity:.5;cursor:not-allowed;transform:none!important;box-shadow:none!important}
.rcard-name{font-weight:800;font-size:.9rem;color:var(--g900);margin-bottom:3px}
.rcard-meta{font-size:.73rem;color:var(--g500);font-weight:600}
.rcard-rev{text-align:right;flex-shrink:0}
.rcard-daily{font-size:.78rem;font-weight:700;color:var(--orange)}
.rcard-monthly{font-size:.72rem;font-weight:600;color:var(--purple)}
.rs-on{display:inline-flex;align-items:center;gap:3px;font-size:.63rem;font-weight:800;
       padding:2px 7px;border-radius:10px;background:#DCFCE7;color:#15803D}
.rs-off{display:inline-flex;align-items:center;gap:3px;font-size:.63rem;font-weight:800;
        padding:2px 7px;border-radius:10px;background:#FEE2E2;color:var(--red)}

/* ── Profile cards ── */
.pf-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px;margin-bottom:14px}
.pf-card{background:#fff;border:1.5px solid var(--g200);border-radius:12px;padding:12px 14px;
         cursor:pointer;transition:.2s;position:relative;overflow:hidden}
.pf-card:hover{border-color:var(--blue);box-shadow:0 4px 14px rgba(27,63,166,.12);transform:translateY(-1px)}
.pf-card.active{border-color:var(--blue);background:linear-gradient(135deg,#EFF6FF,#DBEAFE)}
.pf-card::before{content:'';position:absolute;top:0;left:0;width:4px;height:100%;background:var(--pfc,var(--blue))}
.pf-name{font-size:.78rem;font-weight:900;color:var(--g900);margin-bottom:6px;
         white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.pf-monthly{font-size:.85rem;font-weight:900;color:var(--purple)}
.pf-daily{font-size:.7rem;font-weight:700;color:var(--orange);margin-top:2px}
.pf-cnt{font-size:.65rem;color:var(--g400);font-weight:600;margin-top:3px}
.pf-bar{height:4px;background:var(--g100);border-radius:2px;margin-top:8px;overflow:hidden}
.pf-bar-fill{height:4px;background:linear-gradient(90deg,var(--blue),var(--purple));border-radius:2px;transition:.5s}

/* ── Month/profile tabs (generated by ajax report) ── */
.tk-mth{padding:5px 12px;border-radius:20px;border:1.5px solid var(--g200);background:#fff;
        font-size:.74rem;font-weight:700;cursor:pointer;color:var(--g600);transition:.2s;font-family:inherit}
.tk-mth.active,.tk-mth:hover{background:var(--blue);color:#fff;border-color:var(--blue)}

#detailPanel{display:none}

@media(max-width:600px){
  .rcard{grid-template-columns:1fr}
  .rcard-rev{text-align:left;margin-top:4px}
  .pf-grid{grid-template-columns:1fr 1fr}
}
</style>

<div class="ph">
  <div>
    <div class="ph-t">📈 Laporan Penjualan</div>
    <div class="ph-s">Monitoring pendapatan voucher hotspot — semua router</div>
  </div>
  <a href="/admin/teknisi_portal.php" class="btn bo bsm" style="font-weight:700">← Portal Teknisi</a>
</div>

<!-- ════ PANEL 1: Daftar Router ════ -->
<div id="listPanel">
  <div class="card">
    <div class="ch">
      <div class="ct">🌐 Pilih Router Cabang</div>
    </div>
    <div class="cb" id="routerListWrap">
      <?php if(empty($routers)): ?>
        <div class="alert awrn" style="margin:0">⚠️ Tidak ada router aktif dengan mode Mikhmon diaktifkan.</div>
      <?php else: ?>
        <?php foreach($routers as $r): ?>
        <div class="rcard" data-rid="<?=$r['id']?>" data-rname="<?=h($r['name'])?>">
          <div>
            <div class="rcard-name"><?=h($r['name'])?> <span class="rs-on">🟢 Mikhmon Mode</span></div>
            <div class="rcard-meta"><?=h($r['ip_public']?:'IP tidak diset')?></div>
          </div>
          <div class="rcard-rev">
            <div style="font-size:.75rem;color:var(--blue-d);font-weight:800;background:linear-gradient(135deg,#EFF6FF,#DBEAFE);padding:6px 14px;border-radius:20px;border:1.5px solid #BFDBFE;">Cek Pendapatan →</div>
          </div>
        </div>
        <?php endforeach; ?>
      <?php endif; ?>
    </div>
  </div>
</div>

<!-- ════ PANEL 2: Detail Router ════ -->
<div id="detailPanel">
  <div style="display:flex;align-items:center;gap:10px;margin-bottom:14px;flex-wrap:wrap">
    <button class="btn bo bsm" onclick="showList()" style="font-weight:800">← Semua Router</button>
    <div id="detailTitle" style="font-weight:900;font-size:1rem;color:var(--g900)"></div>
  </div>

  <!-- Per-profil section -->
  <div class="card" style="margin-bottom:14px">
    <div class="ch">
      <div class="ct">📋 Pendapatan Per Profil</div>
      <div id="pfMonthLabel" style="font-size:.73rem;color:var(--g400);font-weight:600"></div>
    </div>
    <div class="cb" id="profileCardsWrap" style="padding:14px">
      <div style="text-align:center;padding:20px;color:var(--g400)">
        <span style="animation:spin 1s linear infinite;display:inline-block">⏳</span>
      </div>
    </div>
  </div>

  <!-- Laporan lengkap -->
  <div class="card">
    <div class="ch"><div class="ct">📅 Laporan Harian &amp; Transaksi</div></div>
    <div id="reportWrap" style="padding:0">
      <div style="text-align:center;padding:24px;color:var(--g400)">
        <span style="animation:spin 1s linear infinite;display:inline-block;font-size:1.4rem">⏳</span>
      </div>
    </div>
  </div>
</div>

<script>
function rp(n){return 'Rp '+Number(n).toLocaleString('id-ID');}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}

let _rid=null, _idbl='';

/* ════ PANEL 1 ════ */
/* Menghapus loadAllRevenue() yang memperlambat halaman */

/* Event delegation — aman dari HTML encoding */
document.getElementById('routerListWrap').addEventListener('click',function(e){
  const card=e.target.closest('.rcard:not(.disabled)');
  if(!card)return;
  openDetail(parseInt(card.dataset.rid), card.dataset.rname||'Router');
});

/* ════ PANEL 2 ════ */
function openDetail(rid,rname){
  _rid=rid; _idbl='';
  document.getElementById('listPanel').style.display='none';
  document.getElementById('detailPanel').style.display='block';
  document.getElementById('detailTitle').textContent='📡 '+rname;
  document.getElementById('profileCardsWrap').innerHTML='<div style="text-align:center;padding:20px;color:var(--g400)"><span style="animation:spin 1s linear infinite;display:inline-block">⏳</span> Memuat profil...</div>';
  document.getElementById('reportWrap').innerHTML='<div style="text-align:center;padding:24px;color:var(--g400)"><span style="animation:spin 1s linear infinite;display:inline-block;font-size:1.4rem">⏳</span><div style="margin-top:8px;font-weight:700">Memuat laporan...</div></div>';
  /* Sequential: profile dulu → report */
  loadProfileRevenue(rid,'').then(()=>loadReport(rid,'',''));
}

function showList(){
  document.getElementById('listPanel').style.display='block';
  document.getElementById('detailPanel').style.display='none';
}

/* ── Profile cards ── */
function loadProfileRevenue(rid,idbl){
  return new Promise(resolve=>{
    let url='/admin/teknisi_laporan_ajax.php?action=profile_revenue&rid='+rid;
    if(idbl)url+='&idbl='+encodeURIComponent(idbl);
    fetch(url).then(r=>r.json()).then(d=>{renderProfileCards(d,rid);resolve();})
      .catch(e=>{document.getElementById('profileCardsWrap').innerHTML='<div class="alert aerr" style="margin:0">❌ '+esc(e.message)+'</div>';resolve();});
  });
}

function renderProfileCards(d,rid){
  const wrap=document.getElementById('profileCardsWrap');
  const lbl=document.getElementById('pfMonthLabel');
  if(d.error){wrap.innerHTML='<div class="alert aerr" style="margin:0">❌ '+esc(d.error)+'</div>';return;}
  _idbl=d.idbl||'';
  if(lbl)lbl.textContent=(d.idbl||'').toUpperCase()+' · '+d.date;
  const profs=d.profiles||[];
  if(!profs.length){wrap.innerHTML='<div class="alert awrn" style="margin:0">📭 Belum ada data penjualan bulan ini.</div>';return;}
  const maxM=Math.max(...profs.map(p=>p.monthly),1);
  const colors=['#1B3FA6','#7C3AED','#D97706','#16A34A','#D42B2B','#0891B2','#EA580C','#4F46E5'];
  let html='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px">'
    +'<div style="background:linear-gradient(135deg,#FFFBEB,#FEF3C7);border:1.5px solid #FDE68A;border-radius:10px;padding:10px 14px">'
    +'<div style="font-size:.63rem;font-weight:700;color:#92400E;text-transform:uppercase;letter-spacing:.4px;margin-bottom:3px">📅 Total Hari Ini</div>'
    +'<div style="font-size:.92rem;font-weight:900;color:var(--orange)">'+rp(d.total_daily)+'</div></div>'
    +'<div style="background:linear-gradient(135deg,#F5F3FF,#EDE9FE);border:1.5px solid #DDD6FE;border-radius:10px;padding:10px 14px">'
    +'<div style="font-size:.63rem;font-weight:700;color:#5B21B6;text-transform:uppercase;letter-spacing:.4px;margin-bottom:3px">📆 Total Bulan Ini</div>'
    +'<div style="font-size:.92rem;font-weight:900;color:var(--purple)">'+rp(d.total_monthly)+'</div></div></div>'
    +'<div style="font-size:.72rem;font-weight:700;color:var(--g500);margin-bottom:10px">📋 '+profs.length+' profil — klik kartu untuk filter laporan di bawah</div>'
    +'<div class="pf-grid">'
    +'<div class="pf-card active" data-prof="" style="--pfc:var(--g400)" onclick="filterProfile('+rid+',\'\',this)">'
    +'<div class="pf-name">📊 Semua Profil</div>'
    +'<div class="pf-monthly">'+rp(d.total_monthly)+'</div>'
    +'<div class="pf-daily">📅 '+rp(d.total_daily)+' hari ini</div>'
    +'<div class="pf-cnt">'+profs.reduce((a,p)=>a+p.count,0)+' transaksi</div>'
    +'<div class="pf-bar"><div class="pf-bar-fill" style="width:100%"></div></div></div>';
  profs.forEach((p,i)=>{
    const col=colors[i%colors.length];
    const pct=Math.round(p.monthly/maxM*100);
    html+='<div class="pf-card" data-prof="'+esc(p.name)+'" style="--pfc:'+col+'" onclick="filterProfile('+rid+',this.dataset.prof,this)">'
      +'<div class="pf-name" title="'+esc(p.name)+'">'+esc(p.name)+'</div>'
      +'<div class="pf-monthly">'+rp(p.monthly)+'</div>'
      +'<div class="pf-daily">📅 '+rp(p.daily)+' hari ini</div>'
      +'<div class="pf-cnt">'+p.count+' transaksi</div>'
      +'<div class="pf-bar"><div class="pf-bar-fill" style="width:'+pct+'%;background:'+col+'"></div></div></div>';
  });
  html+='</div>';
  wrap.innerHTML=html;
}

function filterProfile(rid,profName,cardEl){
  document.querySelectorAll('.pf-card').forEach(c=>c.classList.remove('active'));
  cardEl.classList.add('active');
  loadReport(rid,_idbl,profName);
}

/* ── Report section ── */
function loadReport(rid,idbl,reseller){
  const wrap=document.getElementById('reportWrap');
  wrap.innerHTML='<div style="text-align:center;padding:24px;color:var(--g400)"><span style="animation:spin 1s linear infinite;display:inline-block;font-size:1.4rem">⏳</span></div>';
  let url='/admin/teknisi_laporan_ajax.php?action=report&rid='+rid;
  if(idbl)url+='&idbl='+encodeURIComponent(idbl);
  if(reseller)url+='&reseller='+encodeURIComponent(reseller);
  fetch(url).then(r=>r.text())
    .then(html=>{wrap.innerHTML='<div style="padding:14px 16px;font-size:.85rem">'+html+'</div>';})
    .catch(e=>{wrap.innerHTML='<div class="alert aerr" style="margin:12px">❌ '+esc(e.message)+'</div>';});
}

/* tkRpt: tombol bulan/filter profil di dalam HTML laporan */
function tkRpt(rid,idbl,reseller){
  _idbl=idbl;
  if(!reseller){
    document.querySelectorAll('.pf-card').forEach(c=>c.classList.remove('active'));
    const all=document.querySelector('.pf-card[data-prof=""]');
    if(all)all.classList.add('active');
  }
  loadProfileRevenue(rid,idbl).then(()=>loadReport(rid,idbl,reseller));
}


</script>
<?php endPage(); ?>
